#FROM node:alpine as BUILD_IMAGE
#FROM arm32v7/node as BUILD_IMAGE
#FROM hypriot/rpi-node as BUILD_IMAGE
FROM arm32v6/node:14-alpine3.12 as BUILD_IMAGE


WORKDIR /app

COPY package.json package-lock.json ./

# install dependencies
#RUN npm install -g npm@8.1.4
RUN npm install

COPY . .

# build

#RUN npm run build --max-old-space-size=8192
RUN npm run build

# remove dev dependencies
RUN npm prune --production

FROM  BUILD_IMAGE

WORKDIR /app

# copy from build image
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public

EXPOSE 3000
CMD npm start
