#FROM arm32v7/node:lts-alpine3.12 as BUILD_IMAGE
FROM node:lts-alpine as BUILD_IMAGE
ENV NODE_OPTIONS="--openssl-legacy-provider"
RUN curl -sSf https://gobinaries.com/tj/node-prune | sh


WORKDIR /app

COPY package.json package-lock.json ./

# install dependencies
RUN npm ci

COPY . .

# build
RUN npm run build

# remove dev dependencies
RUN npm prune --production

#FROM arm32v7/node:lts-alpine3.12
FROM node:lts-alpine

WORKDIR /app

# copy from build image
COPY --from=BUILD_IMAGE /app/package.json ./package.json
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public


EXPOSE 3000
CMD npm start
