version: "3.8"

services:

  postgres:
    #image: postgres
    image: timescale/timescaledb:latest-pg15
    #container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      example-network:  
        ipv4_address: 172.16.238.11
  
  mqtt:
    #image: mjenz/rpi-mosquitto:latest
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/password.txt:/mosquitto/config/password.txt
    networks:
      example-network:  
        ipv4_address: 172.16.238.12
        
  backend:
    image: flask
    container_name: flask-backend
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - mqtt
    ports:
      - "5000:5000"
    env_file:
      - disti.env
    networks:
      example-network:
        ipv4_address: 172.16.238.13

  frontend:
    # image: nextjs
    image: jokley/disti-nextjs
    container_name: next-frontend
    privileged: true
    #build:
      #context: ./frontend
    restart: unless-stopped
    ports:
      - "3010:3000"
    networks:
      example-network:
        ipv4_address: 172.16.238.14


  influxdb:
    image: arm32v7/influxdb
    restart: unless-stopped
    env_file:
      - disti.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv:/var/lib/influxdb:rw
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    ports:
      - "8086:8086"
    networks:
      example-network:
        ipv4_address: 172.16.238.16

  telegraf:
    image: arm32v7/telegraf
    restart: unless-stopped
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - disti.env
    networks:
      example-network:
        ipv4_address: 172.16.238.17

  grafana:
    image: grafana/grafana:9.2.3
    restart: unless-stopped
    env_file:
      - disti.env
    depends_on:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/:/etc/grafana
      - ./grafana/plugins/:/var/lib/grafana/plugins
    networks:
      example-network:
        ipv4_address: 172.16.238.18
        
        
  nginx:
    image: arm32v6/nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      example-network:
        ipv4_address: 172.16.238.10

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.16.238.0/24

volumes:
  db_data:
  pgadmin-data:
  influxdbv:
