#FROM python:3.7-alpine
#FROM arm32v7/alpine:3.12
FROM arm32v6/python:3.7.9-alpine3.12

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev build-base

COPY requirements.txt /
RUN pip install -r requirements.txt

COPY . app
WORKDIR /app

ENV FLASK_APP /app.py
CMD gunicorn  SCRIPT_NAME=/backend --bind 0.0.0.0:5000 wsgi:app

EXPOSE 5000
