#FROM python:3.7-alpine
FROM arm64v8/alpine:3.14

RUN apk update
RUN apk add postgresql-dev gcc python3-dev musl-dev build-base

COPY requirements.txt /
RUN pip  install -r requirements.txt

COPY . app
WORKDIR /app

ENV FLASK_APP /app.py
CMD gunicorn --bind 0.0.0.0:5000 wsgi:app 

EXPOSE 5000

