apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: ${POSTGRES_HOST}:5432
    user: ${POSTGRES_USER}

    secureJsonData:
      password: ${POSTGRES_PASSWORD}

    jsonData:
      database: ${POSTGRES_DB}
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
