name: Docker Image CI

on:
  push:
    paths:
      - './frontend/**'
  pull_request:
    paths: 
      - './frontend/**'
#     branches: [ development, dev, qa, latest ]
#   pull_request:
#     branches: [ development, dev, qa, latest ]

 

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKER_USER }}/disti-nextjs:latest
