name: Docker Image CI

on:
  push:
    branches: [ development, dev, qa, latest ]
  pull_request:
    branches: [ development, dev, qa, latest ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
      - 
        name: Extract branch name on push
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - 
        name: Extract branch name on pull request
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/disti-nextjs:$BRANCH_NAME
