name: Docker Image CI

on:
  push:
    branches: [ development, dev, qa, latest ]
  pull_request:
    branches: [ development, dev, qa, latest ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/disti-nextjs:${GITHUB_REF_NAME}
